-- MySQL Script generated by MySQL Workbench
-- 09/08/14 17:22:19
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softwork` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `softwork` ;

-- -----------------------------------------------------
-- Table `softwork`.`Empleado_hoja_De_Vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Empleado_hoja_De_Vida` (
  `Documento` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Sexo` TINYINT NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `Experiencia_laboral` VARCHAR(45) NOT NULL,
  `Estado_civil` VARCHAR(45) NOT NULL,
  `Estado_laboral` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Tipo_de_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Tipo_de_horario` (
  `Id_tipo_horario` VARCHAR(45) NOT NULL,
  `Valor_ horario` INT NOT NULL,
  `Nombre_de_turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_tipo_horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Horario` (
  `IdHorario` INT NOT NULL,
  `Tipo_de_horario_Id tipo horario` VARCHAR(45) NOT NULL,
  `Hora_de_entrada` DATETIME NOT NULL,
  `Hora_de_salida` DATETIME NOT NULL,
  `Huella_dactilar` INT NOT NULL,
  PRIMARY KEY (`IdHorario`),
  INDEX `fk_Horario_Tipo_de_horario1_idx` (`Tipo_de_horario_Id tipo horario` ASC),
  CONSTRAINT `fk_Horario_Tipo_de_horario1`
    FOREIGN KEY (`Tipo_de_horario_Id tipo horario`)
    REFERENCES `softwork`.`Tipo_de_horario` (`Id_tipo_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Capacitacion` (
  `Id_Capacitacion` VARCHAR(45) NOT NULL,
  `Fecha_de_asistencia` INT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Lugar_de_capacitacion` VARCHAR(45) NULL,
  `Duracion` VARCHAR(45) NULL,
  `Hora_de_inicio` TIME NULL,
  `Hora_Finalizacion` TIME NULL,
  PRIMARY KEY (`Id_Capacitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Nomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Nomina` (
  `Id_Nomina` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Subtotal` DECIMAL NULL,
  `Total` DECIMAL NULL,
  PRIMARY KEY (`Id_Nomina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Novedades` (
  `Id_Novedad` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Valor` DECIMAL NULL,
  PRIMARY KEY (`Id_Novedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Historial_de_contratacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Historial_de_contratacion` (
  `Id_Historial_de_contratacion` INT NOT NULL,
  `Fecha_de_ingreso` DATE NULL,
  `Fecha_de_retiro` DATE NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Historial_de_contratacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Empleado_hoja_De_Vida_Historial_de_contratacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Empleado_hoja_De_Vida_Historial_de_contratacion` (
  `Id_contrato` VARCHAR(45) NOT NULL,
  `Historial_de_contratacion_Id_Historial_de_contratacion` INT NULL,
  `Empleado_hoja_De_Vida_Documento` INT NULL,
  PRIMARY KEY (`Id_contrato`),
  INDEX `fk_Empleado_hoja_De_Vida_has_Historial_de_contratacion_Hist_idx` (`Historial_de_contratacion_Id_Historial_de_contratacion` ASC),
  INDEX `fk_Empleado_hoja_De_Vida_has_Historial_de_contratacion_Empl_idx` (`Empleado_hoja_De_Vida_Documento` ASC),
  CONSTRAINT `fk_Empleado_hoja_De_Vida_has_Historial_de_contratacion_Emplea1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_Documento`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_hoja_De_Vida_has_Historial_de_contratacion_Histor1`
    FOREIGN KEY (`Historial_de_contratacion_Id_Historial_de_contratacion`)
    REFERENCES `softwork`.`Historial_de_contratacion` (`Id_Historial_de_contratacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`PreNomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`PreNomina` (
  `Id_preNomina` VARCHAR(45) NOT NULL,
  `Nomina_Id_Nomina` INT NOT NULL,
  `Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_preNomina`, `Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato`),
  INDEX `fk_Detalle_Nomina_Nomina1_idx` (`Nomina_Id_Nomina` ASC),
  INDEX `fk_PreNomina_Empleado_hoja_De_Vida_has_Historial_de_contrat_idx` (`Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato` ASC),
  CONSTRAINT `fk_Detalle_Nomina_Nomina1`
    FOREIGN KEY (`Nomina_Id_Nomina`)
    REFERENCES `softwork`.`Nomina` (`Id_Nomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreNomina_Empleado_hoja_De_Vida_has_Historial_de_contratac1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida_Historial_de_contratacion` (`Id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Capacitacion_Hoja_de_vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Capacitacion_Hoja_de_vida` (
  `Id_hojavida_capacitacion` VARCHAR(45) NOT NULL,
  `Id_capacitaciones` VARCHAR(45) NOT NULL,
  `Hojas_de_vida_Empleados_Documento` INT NOT NULL,
  `Capacitacion_id_Capacitacion` VARCHAR(45) NOT NULL,
  `Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_hojavida_capacitacion`, `Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato`),
  INDEX `fk_Capacitacion_Hoja_de_vida_Capacitacion1_idx` (`Capacitacion_id_Capacitacion` ASC),
  INDEX `fk_Capacitacion_Hoja_de_vida_Empleado_hoja_De_Vida_has_Hist_idx` (`Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato` ASC),
  CONSTRAINT `fk_Capacitacion_Hoja_de_vida_Capacitacion1`
    FOREIGN KEY (`Capacitacion_id_Capacitacion`)
    REFERENCES `softwork`.`Capacitacion` (`Id_Capacitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Capacitacion_Hoja_de_vida_Empleado_hoja_De_Vida_has_Histor1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_has_Historial_de_contratacion_Id_contrato`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida_Historial_de_contratacion` (`Id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Horario_prenomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Horario_prenomina` (
  `Id-Horario_Empleado` VARCHAR(45) NOT NULL,
  `IdHorario` INT NOT NULL,
  `PreNomina_Id_preNomina` VARCHAR(45) NOT NULL,
  INDEX `fk_Horario_has_Empleados_Horario1_idx` (`IdHorario` ASC),
  PRIMARY KEY (`Id-Horario_Empleado`),
  INDEX `fk_Horario_Empleado_PreNomina1_idx` (`PreNomina_Id_preNomina` ASC),
  CONSTRAINT `fk_Horario_has_Empleados_Horario1`
    FOREIGN KEY (`IdHorario`)
    REFERENCES `softwork`.`Horario` (`IdHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Empleado_PreNomina1`
    FOREIGN KEY (`PreNomina_Id_preNomina`)
    REFERENCES `softwork`.`PreNomina` (`Id_preNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Valor_Hora_Extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Valor_Hora_Extra` (
  `IdValor_Hora_Extra` INT NOT NULL,
  `Valor_Nocturna` INT NULL,
  `Valor_Diurna` INT NULL,
  `Valor_Festivos` INT NULL,
  `Valor_Dominicales` INT NULL,
  PRIMARY KEY (`IdValor_Hora_Extra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Estudio` (
  `Id_Estudio` INT NOT NULL,
  `Estudios` VARCHAR(45) NULL,
  `Nivel_De_Estudio` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Estudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Estudio_Hoja_de_vida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Estudio_Hoja_de_vida` (
  `Id_Estudio_hoja_de_Vida` VARCHAR(45) NOT NULL,
  `Estudio_Id_Estudio` INT NOT NULL,
  `Id_Hoja_de_vida` VARCHAR(45) NOT NULL,
  `Documento` INT NOT NULL,
  `Empleado_hoja_De_Vida_Documento` INT NOT NULL,
  PRIMARY KEY (`Id_Estudio_hoja_de_Vida`),
  INDEX `fk_Estudio_has_Hoja_de_vida_Estudio1_idx` (`Estudio_Id_Estudio` ASC),
  INDEX `fk_Estudio_has_Hoja_de_vida_Empleado_hoja_De_Vida1_idx` (`Empleado_hoja_De_Vida_Documento` ASC),
  CONSTRAINT `fk_Estudio_has_Hoja_de_vida_Estudio1`
    FOREIGN KEY (`Estudio_Id_Estudio`)
    REFERENCES `softwork`.`Estudio` (`Id_Estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudio_has_Hoja_de_vida_Empleado_hoja_De_Vida1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_Documento`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Referencia` (
  `Id_Referencia` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Ocupacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Hoja_de_vida_has_Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Hoja_de_vida_has_Referencia` (
  `Id_hoja_de_Vida_referencia` INT NOT NULL,
  `Id_Hoja_de_vida` VARCHAR(45) NOT NULL,
  `Documento` INT NOT NULL,
  `Id_Referencia` INT NOT NULL,
  `Empleado_hoja_De_Vida_Documento` INT NOT NULL,
  INDEX `fk_Hoja_de_vida_has_Referencia_Referencia1_idx` (`Id_Referencia` ASC),
  PRIMARY KEY (`Id_hoja_de_Vida_referencia`),
  INDEX `fk_Hoja_de_vida_has_Referencia_Empleado_hoja_De_Vida1_idx` (`Empleado_hoja_De_Vida_Documento` ASC),
  CONSTRAINT `fk_Hoja_de_vida_has_Referencia_Referencia1`
    FOREIGN KEY (`Id_Referencia`)
    REFERENCES `softwork`.`Referencia` (`Id_Referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hoja_de_vida_has_Referencia_Empleado_hoja_De_Vida1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_Documento`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Entrada y salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Entrada y salida` (
  `Id_entrada_salida` VARCHAR(45) NOT NULL,
  `Fecha` DATE NULL,
  `Hora_entrada` TIME NULL,
  `Hora_Salida` TIME NULL,
  `PreNomina_Id_preNomina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_entrada_salida`),
  INDEX `fk_Entrada y salida_PreNomina1_idx` (`PreNomina_Id_preNomina` ASC),
  CONSTRAINT `fk_Entrada y salida_PreNomina1`
    FOREIGN KEY (`PreNomina_Id_preNomina`)
    REFERENCES `softwork`.`PreNomina` (`Id_preNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Valoracion` (
  `Id_Valoracion` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Valoracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Empleado_hoja_De_Vida_has_Valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Empleado_hoja_De_Vida_has_Valoracion` (
  `Empleado_hoja_De_Vida_Documento` INT NOT NULL,
  `Valoracion_Id_Valoracion` INT NOT NULL,
  PRIMARY KEY (`Empleado_hoja_De_Vida_Documento`, `Valoracion_Id_Valoracion`),
  INDEX `fk_Empleado_hoja_De_Vida_has_Valoracion_Valoracion1_idx` (`Valoracion_Id_Valoracion` ASC),
  INDEX `fk_Empleado_hoja_De_Vida_has_Valoracion_Empleado_hoja_De_Vi_idx` (`Empleado_hoja_De_Vida_Documento` ASC),
  CONSTRAINT `fk_Empleado_hoja_De_Vida_has_Valoracion_Empleado_hoja_De_Vida1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_Documento`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_hoja_De_Vida_has_Valoracion_Valoracion1`
    FOREIGN KEY (`Valoracion_Id_Valoracion`)
    REFERENCES `softwork`.`Valoracion` (`Id_Valoracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Irregularidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Irregularidades` (
  `idNovedades` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idNovedades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Novedades_Irregularidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Novedades_Irregularidades` (
  `Novedades_idNovedades` INT NOT NULL,
  `Entrada y salida_Id_entrada_salida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Novedades_idNovedades`, `Entrada y salida_Id_entrada_salida`),
  INDEX `fk_Novedades_has_Entrada y salida_Entrada y salida1_idx` (`Entrada y salida_Id_entrada_salida` ASC),
  INDEX `fk_Novedades_has_Entrada y salida_Novedades1_idx` (`Novedades_idNovedades` ASC),
  CONSTRAINT `fk_Novedades_has_Entrada y salida_Novedades1`
    FOREIGN KEY (`Novedades_idNovedades`)
    REFERENCES `softwork`.`Irregularidades` (`idNovedades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Novedades_has_Entrada y salida_Entrada y salida1`
    FOREIGN KEY (`Entrada y salida_Id_entrada_salida`)
    REFERENCES `softwork`.`Entrada y salida` (`Id_entrada_salida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Novedades` (
  `Id_Novedad` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Valor` DECIMAL NULL,
  PRIMARY KEY (`Id_Novedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`PreNomina_has_Novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`PreNomina_has_Novedades` (
  `PreNomina_Id_preNomina` VARCHAR(45) NOT NULL,
  `Novedades_Id_Novedad` INT NOT NULL,
  PRIMARY KEY (`PreNomina_Id_preNomina`, `Novedades_Id_Novedad`),
  INDEX `fk_PreNomina_has_Novedades_Novedades1_idx` (`Novedades_Id_Novedad` ASC),
  INDEX `fk_PreNomina_has_Novedades_PreNomina1_idx` (`PreNomina_Id_preNomina` ASC),
  CONSTRAINT `fk_PreNomina_has_Novedades_PreNomina1`
    FOREIGN KEY (`PreNomina_Id_preNomina`)
    REFERENCES `softwork`.`PreNomina` (`Id_preNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreNomina_has_Novedades_Novedades1`
    FOREIGN KEY (`Novedades_Id_Novedad`)
    REFERENCES `softwork`.`Novedades` (`Id_Novedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Deduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Deduccion` (
  `Id_Deduccion` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Porcentaje` FLOAT NULL,
  PRIMARY KEY (`Id_Deduccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`PreNomina_has_Deduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`PreNomina_has_Deduccion` (
  `PreNomina_Id_preNomina` VARCHAR(45) NOT NULL,
  `Deduccion_Id_Deduccion` INT NOT NULL,
  PRIMARY KEY (`PreNomina_Id_preNomina`, `Deduccion_Id_Deduccion`),
  INDEX `fk_PreNomina_has_Deduccion_Deduccion1_idx` (`Deduccion_Id_Deduccion` ASC),
  INDEX `fk_PreNomina_has_Deduccion_PreNomina1_idx` (`PreNomina_Id_preNomina` ASC),
  CONSTRAINT `fk_PreNomina_has_Deduccion_PreNomina1`
    FOREIGN KEY (`PreNomina_Id_preNomina`)
    REFERENCES `softwork`.`PreNomina` (`Id_preNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreNomina_has_Deduccion_Deduccion1`
    FOREIGN KEY (`Deduccion_Id_Deduccion`)
    REFERENCES `softwork`.`Deduccion` (`Id_Deduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Rol` (
  `IdRol` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `Rol_IdRol` INT NOT NULL,
  `Empleado_hoja_De_Vida_Documento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `frase_secreta` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_IdRol` ASC),
  INDEX `fk_Usuario_Empleado_hoja_De_Vida1_idx` (`Empleado_hoja_De_Vida_Documento` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_IdRol`)
    REFERENCES `softwork`.`Rol` (`IdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empleado_hoja_De_Vida1`
    FOREIGN KEY (`Empleado_hoja_De_Vida_Documento`)
    REFERENCES `softwork`.`Empleado_hoja_De_Vida` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Modulo` (
  `IdModulo` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`IdModulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwork`.`Modulo_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwork`.`Modulo_Rol` (
  `Modulo_IdModulo` INT NOT NULL,
  `Rol_IdRol` INT NOT NULL,
  INDEX `fk_Modulo_has_Rol_Rol1_idx` (`Rol_IdRol` ASC),
  INDEX `fk_Modulo_has_Rol_Modulo1_idx` (`Modulo_IdModulo` ASC),
  CONSTRAINT `fk_Modulo_has_Rol_Modulo1`
    FOREIGN KEY (`Modulo_IdModulo`)
    REFERENCES `softwork`.`Modulo` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modulo_has_Rol_Rol1`
    FOREIGN KEY (`Rol_IdRol`)
    REFERENCES `softwork`.`Rol` (`IdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
